# (table, column) -> {"meaning": str, "usage": str optional, "notes": str optional}
FIELDS: dict[tuple[str, str], dict[str, str]] = {
    ("app_user", "id"): {"meaning": 'รหัสประจำผู้ใช้ OMS (UUIDv7)'},
    ("app_user", "tsf_user_id"): {"meaning": 'รหัสผู้ใช้บน TSF (ไม่ซ้ำทั้งระบบ)'},
    ("app_user", "email"): {"meaning": 'อีเมลผู้ใช้จาก TSF', "notes": 'PII 🔒'},
    ("app_user", "display_name"): {"meaning": 'ชื่อที่แสดงของผู้ใช้', "notes": 'PII 🔒'},
    ("app_user", "last_login_at"): {"meaning": 'เวลา login ล่าสุด (UTC)'},
    ("audit_log", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("audit_log", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("audit_log", "actor_type"): {"meaning": 'ประเภทผู้กระทำ', "notes": 'enum: USER, SYSTEM, TSF, PLATFORM_ADMIN'},
    ("audit_log", "actor_id"): {"meaning": 'รหัสผู้กระทำ (text)'},
    ("audit_log", "action"): {"meaning": 'รหัสการกระทำ — เช่น `auth.login`, `membership.changed`, `PRODUCT_CREATED`/`PRODUCT_UPDATED`/`PRODUCT_ARCHIVED`/`PRODUCT_DELETED`, `SKU_CREATED`/`SKU_UPDATED`/`SKU_DELETED`, `CATALOG_IMPORTED`, `CHANNEL_LISTING_MAPPED`/`CHANNEL_LISTING_UNMAPPED`, `ORDER_CANCEL_REQUESTED`, `ORDER_HOLD_RECHECKED`, `outbox.retry`'},
    ("audit_log", "entity_type"): {"meaning": 'ประเภท entity ที่ถูก audit'},
    ("audit_log", "entity_id"): {"meaning": 'รหัส entity'},
    ("audit_log", "before"): {"meaning": 'snapshot ก่อนเปลี่ยน (JSON)'},
    ("audit_log", "after"): {"meaning": 'snapshot หลังเปลี่ยน (JSON)'},
    ("audit_log", "ip"): {"meaning": 'ที่อยู่ IP ผู้เรียก', "notes": 'PII 🔒'},
    ("audit_log", "created_at"): {"meaning": 'เวลาที่บันทึก audit (UTC)', "notes": 'append-only'},
    ("channel_account", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("channel_account", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("channel_account", "channel"): {"meaning": 'ช่องทางขาย', "notes": 'enum: TSF, SHOPEE, LAZADA, TIKTOK'},
    ("channel_account", "external_shop_id"): {"meaning": 'รหัสร้านฝั่งช่องทาง (unique กับ channel)'},
    ("channel_account", "mode"): {"meaning": 'โหมดควบคุมสต็อก/สังเกตการณ์', "notes": 'enum: OBSERVE, SHADOW, CONTROL, ACTIVE'},
    ("channel_account", "stock_sync_paused"): {"meaning": 'หยุด push สต็อกไปช่องทางชั่วคราว (true = หยุด)'},
    ("channel_account", "status"): {"meaning": 'สถานะการเชื่อมต่อบัญชี', "notes": 'enum: CONNECTED, DISCONNECTED'},
    ("channel_account", "credentials_ref"): {"meaning": 'ชื่อ secret ใน secret manager (ไม่เก็บ token ในฐานข้อมูล)'},
    ("channel_account", "token_expires_at"): {"meaning": 'เวลาหมดอายุ token OAuth (UTC)'},
    ("channel_account", "last_synced_at"): {"meaning": 'เวลา sync ช่องทางสำเร็จล่าสุด (UTC)'},
    ("channel_account", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("channel_account", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("channel_listing", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("channel_listing", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("channel_listing", "channel_account_id"): {"meaning": 'บัญชีช่องทางขายที่แถวอ้างอิง'},
    ("channel_listing", "sku_id"): {"meaning": 'SKU OMS ที่แถวอ้างอิง'},
    ("channel_listing", "external_item_id"): {"meaning": 'รหัส item ฝั่งช่องทาง (ถ้ามี)'},
    ("channel_listing", "external_sku_id"): {"meaning": 'รหัส SKU/listing ฝั่งช่องทาง'},
    ("channel_listing", "stock_control"): {"meaning": 'เมื่อ true และ channel เป็น CONTROL — บังคับตรวจสต็อก/จอง hold ที่ intake และ checkout'},
    ("channel_listing", "safety_buffer"): {"meaning": 'จำนวนหักจาก sellable ก่อนคำนวณ channel_exposed (checkout availability วันนี้)'},
    ("channel_listing", "last_exposed_qty"): {"meaning": 'จำนวนสต็อกที่ push ไปช่องทางครั้งล่าสุด', "notes": 'reserved [T15](../plan/05-task-list.md#L216) — ยังไม่มี writer บน main'},
    ("channel_listing", "last_pushed_version"): {"meaning": 'เวอร์ชัน push สต็อกล่าสุดไปช่องทาง', "notes": 'reserved [T15](../plan/05-task-list.md#L216) — ยังไม่มี writer บน main'},
    ("channel_listing", "last_seen_channel_qty"): {"meaning": 'จำนวนสต็อกที่เห็นจากช่องทางล่าสุด', "notes": 'reserved [T23](../plan/05-task-list.md#L245) — ยังไม่มี writer บน main'},
    ("channel_listing", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("channel_listing", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("channel_listing", "seller_sku"): {"meaning": 'รหัส SKU ที่ผู้ขายตั้งบนช่องทาง'},
    ("channel_listing", "name"): {"meaning": 'ชื่อ listing จากช่องทาง'},
    ("channel_listing", "mapping_source"): {"meaning": 'วิธีที่แมป listing กับ SKU OMS', "notes": 'enum: AUTO, MANUAL หรือ NULL ก่อนแมป'},
    ("channel_listing", "mapped_at"): {"meaning": 'เวลาที่แมป SKU สำเร็จ (UTC)'},
    ("channel_listing", "removed_at"): {"meaning": 'เวลาที่ listing หายจากช่องทาง (soft delete)'},
    ("idempotency_key", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("idempotency_key", "scope"): {"meaning": 'ขอบเขตคีย์ (เช่น checkout, stock)'},
    ("idempotency_key", "key"): {"meaning": 'คีย์ idempotency จาก client'},
    ("idempotency_key", "request_hash"): {"meaning": 'hash ของ request กันคีย์เดียวคนละ body'},
    ("idempotency_key", "response_status"): {"meaning": 'HTTP status ที่ replay'},
    ("idempotency_key", "response_body"): {"meaning": 'body JSON ที่ replay'},
    ("idempotency_key", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("inbox_event", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("inbox_event", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("inbox_event", "source"): {"meaning": 'แหล่ง event (เช่น TSF)'},
    ("inbox_event", "event_id"): {"meaning": 'รหัส event จากแหล่ง (dedup ต่อ tenant)'},
    ("inbox_event", "event_type"): {"meaning": 'ชนิด event สำหรับ router handler'},
    ("inbox_event", "aggregate_id"): {"meaning": 'รหัส aggregate ที่ event เกี่ยว'},
    ("inbox_event", "payload"): {"meaning": 'เนื้อหา event เป็น JSON (อาจมี PII ชั่วคราว)', "notes": 'PII 🔒 — scrub หลัง 7 วัน วางแผน [T27](../plan/05-task-list.md#L224) (05-task-list); ยังไม่ implement บน main'},
    ("inbox_event", "status"): {"meaning": 'สถานะคิว: RECEIVED รอ worker, PROCESSED สำเร็จ, FAILED รอ retry, DEAD หยุด retry', "notes": 'enum: RECEIVED, PROCESSED, FAILED, DEAD'},
    ("inbox_event", "attempts"): {"meaning": 'จำนวนครั้งที่ worker หยิบ/ลองแล้ว'},
    ("inbox_event", "next_attempt_at"): {"meaning": 'เวลา lease/retry ถัดไป (claim_inbox_batch ขยับ)'},
    ("inbox_event", "last_error"): {"meaning": 'ข้อความ error ล่าสุด'},
    ("inbox_event", "received_at"): {"meaning": 'เวลารับ event เข้าระบบ (UTC)'},
    ("inbox_event", "processed_at"): {"meaning": 'เวลาประมวลผลสำเร็จ (UTC)'},
    ("inbox_event", "aggregate_version"): {"meaning": 'เวอร์ชัน envelope; 0 = ผู้ส่งไม่ส่ง; กัน replay เก่า'},
    ("inbox_event", "payload_sha256"): {"meaning": 'SHA-256 ของ body ครั้งแรก; event_id ซ้ำแต่ hash ต่างยังถือ duplicate'},
    ("inbox_event", "orphan_recorded_at"): {"meaning": 'เวลาที่บันทึกว่าเป็น orphan หลัง defer เกิน max'},
    ("inventory", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("inventory", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("inventory", "sku_id"): {"meaning": 'SKU OMS ที่แถวอ้างอิง'},
    ("inventory", "warehouse_id"): {"meaning": 'คลังที่แถวอ้างอิง'},
    ("inventory", "on_hand"): {"meaning": 'จำนวนสต็อกคงเหลือจริงในคลัง'},
    ("inventory", "reserved"): {"meaning": 'จำนวนที่จองไว้แล้ว (reserved ≤ on_hand)'},
    ("inventory", "stock_version"): {"meaning": 'เวอร์ชัน monotonic บวกทุกการเปลี่ยนสต็อก — ใช้เรียง/ส่ง `stock.updated` ([T15](../plan/05-task-list.md#L216), 04-api-contract); ไม่ใช่ optimistic lock (ล็อกแถว FOR UPDATE)'},
    ("inventory", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("inventory", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("inventory", "ledger_seq"): {"meaning": 'จำนวนแถว ledger ที่ commit แล้วสำหรับ (sku, warehouse) นี้'},
    ("inventory_ledger", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("inventory_ledger", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("inventory_ledger", "sku_id"): {"meaning": 'SKU OMS ที่แถวอ้างอิง'},
    ("inventory_ledger", "warehouse_id"): {"meaning": 'คลังที่แถวอ้างอิง'},
    ("inventory_ledger", "delta_on_hand"): {"meaning": 'การเปลี่ยน on_hand ในรายการนี้ (+/-)'},
    ("inventory_ledger", "delta_reserved"): {"meaning": 'การเปลี่ยน reserved ในรายการนี้ (+/-)'},
    ("inventory_ledger", "reason"): {"meaning": 'เหตุผลทางบัญชีสต็อก', "notes": 'enum: OPENING_BALANCE, RECEIVE, ADJUST_IN, ADJUST_OUT, COUNT_CORRECTION, DAMAGE_WRITE_OFF, RETURN_RESTOCK, SHIP, RESERVE, RELEASE, UNPACK; append-only'},
    ("inventory_ledger", "ref_type"): {"meaning": 'ประเภทอ้างอิงต้นทาง (เช่น reservation, document)'},
    ("inventory_ledger", "ref_id"): {"meaning": 'รหัสอ้างอิงต้นทาง (คู่กับ ref_type)'},
    ("inventory_ledger", "actor"): {"meaning": 'ผู้กระทำหรือระบบที่ทำให้เกิดรายการ'},
    ("inventory_ledger", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("inventory_ledger", "ledger_seq"): {"meaning": 'ลำดับ monotonic ต่อ (tenant, sku, warehouse) ใช้เรียงประวัติแทน created_at', "notes": 'append-only'},
    ("order_hold_retry", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("order_hold_retry", "order_id"): {"meaning": 'ออเดอร์ SKU_NOT_MAPPED ที่ scheduled sweeper จะลองอีก (PK)'},
    ("order_hold_retry", "attempts"): {"meaning": 'จำนวนรอบ backoff ที่ scheduled sweeper บันทึกแล้ว'},
    ("order_hold_retry", "next_attempt_at"): {"meaning": 'เวลาที่ scheduled sweeper จะลอง resolve อีก'},
    ("order_hold_retry", "last_error"): {"meaning": 'โค้ดผลล่าสุด: `STILL_HELD`, `DEFERRED`, หรือ simple name ของ exception (ไม่ใช่ข้อความ error)'},
    ("order_hold_retry", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("order_line", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("order_line", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("order_line", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด'},
    ("order_line", "sku_id"): {"meaning": 'SKU OMS ที่แมปแล้ว (NULL ถ้ายังไม่แมป → hold SKU_NOT_MAPPED)'},
    ("order_line", "external_line_id"): {"meaning": 'รหัสบรรทัดฝั่งช่องทาง'},
    ("order_line", "external_sku_id"): {"meaning": 'รหัส SKU ฝั่งช่องทางบนบรรทัด'},
    ("order_line", "name"): {"meaning": 'ชื่อสินค้าบนบรรทัด'},
    ("order_line", "qty"): {"meaning": 'จำนวนที่สั่ง'},
    ("order_line", "unit_price"): {"meaning": 'ราคาต่อหน่วย (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("order_line", "discount"): {"meaning": 'ส่วนลดบรรทัด (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("order_line", "line_total"): {"meaning": 'ยอดรวมบรรทัด (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("order_line", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("order_line", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("order_recipient", "order_id"): {"meaning": 'รหัสออเดอร์ (PK คู่กับแถว PII หนึ่งต่อ order)'},
    ("order_recipient", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("order_recipient", "name_enc"): {"meaning": 'ชื่อผู้รับเข้ารหัส AES-256-GCM', "notes": 'PII 🔒 ciphertext'},
    ("order_recipient", "phone_enc"): {"meaning": 'เบอร์โทรเข้ารหัส AES-256-GCM', "notes": 'PII 🔒 ciphertext'},
    ("order_recipient", "phone_hash"): {"meaning": 'HMAC-SHA256 ของเบอร์ normalize ใช้ค้นหา', "notes": 'PII 🔒'},
    ("order_recipient", "phone_last4"): {"meaning": 'เลข 4 ตัวท้ายเบอร์โทร (plaintext)', "notes": 'PII 🔒'},
    ("order_recipient", "address_enc"): {"meaning": 'ที่อยู่เข้ารหัส AES-256-GCM', "notes": 'PII 🔒 ciphertext'},
    ("order_recipient", "province"): {"meaning": 'จังหวัด (plaintext; คงไว้หลัง redact)'},
    ("order_recipient", "postcode"): {"meaning": 'รหัสไปรษณีย์ (plaintext; คงไว้หลัง redact)'},
    ("order_recipient", "pii_status"): {"meaning": 'สถานะวงจร PII', "notes": 'enum: ACTIVE, REDACTED'},
    ("order_recipient", "redact_after"): {"meaning": 'เวลานัดลบ/ทำให้ไม่ระบุตัวตน (PDPA)'},
    ("order_recipient", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("order_recipient", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("order_status_history", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("order_status_history", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("order_status_history", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด'},
    ("order_status_history", "dimension"): {"meaning": 'มิติสถานะที่เปลี่ยน', "notes": 'enum: ORDER, PAYMENT, FULFILLMENT, HOLD'},
    ("order_status_history", "from_value"): {"meaning": 'ค่าก่อนเปลี่ยน (NULL สำหรับครั้งแรกของมิติ)'},
    ("order_status_history", "to_value"): {"meaning": 'ค่าหลังเปลี่ยน'},
    ("order_status_history", "reason"): {"meaning": 'เหตุผลประกอบการเปลี่ยนสถานะ'},
    ("order_status_history", "actor"): {"meaning": 'ผู้กระทำหรือระบบที่เปลี่ยนสถานะ'},
    ("order_status_history", "created_at"): {"meaning": 'เวลาที่บันทึกการเปลี่ยนสถานะ (UTC)', "notes": 'append-only'},
    ("outbox_event", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("outbox_event", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("outbox_event", "aggregate_type"): {"meaning": 'ประเภท aggregate ใน outbox'},
    ("outbox_event", "aggregate_id"): {"meaning": 'รหัส aggregate'},
    ("outbox_event", "event_type"): {"meaning": 'ชนิด event ที่จะส่งออก'},
    ("outbox_event", "payload"): {"meaning": 'payload JSON ที่จะส่งไป TSF (อาจมี PII ชั่วคราว)', "notes": 'PII 🔒 — scrub หลัง 7 วัน วางแผน [T27](../plan/05-task-list.md#L224); ยังไม่ implement บน main'},
    ("outbox_event", "status"): {"meaning": 'PENDING รอส่ง, IN_FLIGHT worker ถือ lease, SENT สำเร็จ, DEAD หยุด retry (admin retry ได้)'},
    ("outbox_event", "attempts"): {"meaning": 'จำนวนครั้งที่พยายามส่ง'},
    ("outbox_event", "next_attempt_at"): {"meaning": 'เวลา retry ส่งถัดไป'},
    ("outbox_event", "lease_until"): {"meaning": 'หมด lease ตอน worker ถือ IN_FLIGHT'},
    ("outbox_event", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("outbox_event", "sent_at"): {"meaning": 'เวลาส่งสำเร็จ (UTC)'},
    ("payment_status_snapshot", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "provider"): {"meaning": 'ผู้ให้บริการชำระเงิน', "notes": 'enum: XENDIT, OPN; reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "provider_ref"): {"meaning": 'อ้างอิงจาก payment provider', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "status"): {"meaning": 'สถานะดิบจาก provider (ไม่ enumerate ใน schema)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "amount"): {"meaning": 'ยอดชำระ (บาท)', "notes": 'เงิน THB numeric(14,2); reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "refunded_amount"): {"meaning": 'ยอดที่ refund แล้ว (บาท)', "notes": 'เงิน THB numeric(14,2); reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "currency"): {"meaning": 'สกุลเงินของ snapshot (schema คาด THB)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "paid_at"): {"meaning": 'เวลาชำระสำเร็จ (UTC)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "observed_at"): {"meaning": 'เวลาที่สะท้อนจาก provider (UTC)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("payment_status_snapshot", "source_event_id"): {"meaning": 'event id จาก inbox ใช้ dedup', "notes": 'reserved [T21](../plan/05-task-list.md#L237); append-only'},
    ("payment_status_snapshot", "created_at"): {"meaning": 'เวลาที่บันทึก snapshot (UTC)', "notes": 'append-only; reserved [T21](../plan/05-task-list.md#L237)'},
    ("product", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("product", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("product", "name"): {"meaning": 'ชื่อที่แสดง'},
    ("product", "status"): {"meaning": 'สถานะสินค้าในแคตตาล็อก', "notes": 'enum: ACTIVE, INACTIVE'},
    ("product", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("product", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("reconciliation_issue", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("reconciliation_issue", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("reconciliation_issue", "run_id"): {"meaning": 'รหัสรอบ reconcile (ยังไม่มีตาราง run)'},
    ("reconciliation_issue", "rule"): {"meaning": 'กฎที่ตรวจแล้วพบปัญหา'},
    ("reconciliation_issue", "order_id"): {"meaning": 'ออเดอร์ที่เกี่ยว (NULL = ระดับร้าน)'},
    ("reconciliation_issue", "details"): {"meaning": 'รายละเอียด JSON (ห้าม PII)'},
    ("reconciliation_issue", "status"): {"meaning": 'สถานะการจัดการ', "notes": 'enum: OPEN, ACK, RESOLVED'},
    ("reconciliation_issue", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("reconciliation_issue", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("refund", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "return_id"): {"meaning": 'คำขอคืนที่เกี่ยว (ถ้ามี)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "provider_ref"): {"meaning": 'อ้างอิงจาก payment provider', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "amount"): {"meaning": 'จำนวนเงินคืน (บาท)', "notes": 'เงิน THB numeric(14,2); reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "currency"): {"meaning": 'สกุลเงินของ refund (schema คาด THB)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "status"): {"meaning": 'สถานะ refund จาก TSF Pay', "notes": 'enum: PENDING, SUCCEEDED, FAILED; reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "observed_at"): {"meaning": 'เวลาที่สะท้อนจาก provider (UTC)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "source_event_id"): {"meaning": 'event id จาก inbox ใช้ dedup', "notes": 'reserved [T21](../plan/05-task-list.md#L237); unique ต่อ tenant'},
    ("refund", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("refund", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)', "notes": 'reserved [T21](../plan/05-task-list.md#L237)'},
    ("return_line", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "return_id"): {"meaning": 'คำขอคืนที่บรรทัดนี้สังกัด', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "order_line_id"): {"meaning": 'บรรทัดออเดอร์ที่คืน', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "qty"): {"meaning": 'จำนวนที่ขอคืน', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "condition"): {"meaning": 'สภาพสินค้าเมื่อรับคืน', "notes": 'enum: RESELLABLE, DAMAGED หรือ NULL ก่อนรับ; reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "restocked_qty"): {"meaning": 'จำนวนที่นำกลับเข้าสต็อกแล้ว', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_line", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "order_id"): {"meaning": 'ออเดอร์ที่แถวนี้สังกัด', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "external_return_id"): {"meaning": 'รหัสคืนสินค้าจากช่องทาง', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "type"): {"meaning": 'ประเภทคำขอ', "notes": 'enum: RETURN, RTS; reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "status"): {"meaning": 'สถานะคำขอ', "notes": 'enum: REQUESTED, APPROVED, REJECTED, RECEIVED, CLOSED; reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "rejected"): {"meaning": 'เคยถูกปฏิเสธแล้ว (sticky ไม่ล้าง)', "notes": 'reserved [T20](../plan/05-task-list.md#L233) — trigger return_request_rejected_guard'},
    ("return_request", "reason"): {"meaning": 'เหตุผลที่ขอคืน', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "requested_at"): {"meaning": 'เวลายื่นคำขอ (UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "received_at"): {"meaning": 'เวลารับสินค้าคืน (UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("return_request", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)', "notes": 'reserved [T20](../plan/05-task-list.md#L233)'},
    ("sales_order", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("sales_order", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("sales_order", "channel_account_id"): {"meaning": 'บัญชีช่องทางขายที่แถวอ้างอิง'},
    ("sales_order", "external_order_id"): {"meaning": 'รหัสออเดอร์ฝั่งช่องทาง'},
    ("sales_order", "order_status"): {"meaning": 'สถานะชีวิตออเดอร์', "notes": 'enum: ACTIVE, CANCELLED, COMPLETED'},
    ("sales_order", "payment_status"): {"meaning": 'สถานะการชำระเงินที่ OMS derive', "notes": 'enum: PENDING, PAID, COD_PENDING, PARTIALLY_REFUNDED, REFUNDED'},
    ("sales_order", "fulfillment_status"): {"meaning": 'สถานะการจัดส่ง/fulfillment', "notes": 'enum: UNFULFILLED, READY_TO_PICK, PICKING, PACKED, SHIPPED, DELIVERED'},
    ("sales_order", "hold_reason"): {"meaning": 'เหตุผลที่ออเดอร์ถูก hold', "notes": 'enum: NONE, SKU_NOT_MAPPED, OUT_OF_STOCK, ADDRESS_PROBLEM, PAYMENT_MISMATCH, CHANNEL_CANCEL_PENDING, MANUAL'},
    ("sales_order", "hold_note"): {"meaning": 'หมายเหตุเพิ่มเมื่อ hold (เช่น MANUAL)'},
    ("sales_order", "channel_status"): {"meaning": 'ข้อความสถานะดิบจากช่องทาง'},
    ("sales_order", "payment_method"): {"meaning": 'วิธีชำระ', "notes": 'enum: PREPAID, COD'},
    ("sales_order", "currency"): {"meaning": 'สกุลเงินออเดอร์ — CHECK บังคับ `THB` เท่านั้นบน main'},
    ("sales_order", "subtotal"): {"meaning": 'ยอดรวมสินค้า (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("sales_order", "shipping_fee"): {"meaning": 'ค่าจัดส่ง (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("sales_order", "discount"): {"meaning": 'ส่วนลด (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("sales_order", "grand_total"): {"meaning": 'ยอดสุทธิออเดอร์ (บาท)', "notes": 'เงิน THB numeric(14,2)'},
    ("sales_order", "ordered_at"): {"meaning": 'เวลาที่ลูกค้าสั่ง (UTC)'},
    ("sales_order", "paid_at"): {"meaning": 'เวลาชำระเงินสำเร็จ (UTC)'},
    ("sales_order", "ship_by"): {"meaning": 'กำหนดส่งล่าสุดจากช่องทาง (UTC)'},
    ("sales_order", "completed_at"): {"meaning": 'เวลาออเดอร์ปิดงาน (UTC)', "notes": 'reserved — ไม่มี writer/reader บน main'},
    ("sales_order", "external_version"): {"meaning": 'เวอร์ชัน aggregate จากช่องทาง ใช้ dedup inbox'},
    ("sales_order", "version"): {"meaning": 'เวอร์ชัน optimistic lock ของออเดอร์'},
    ("sales_order", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("sales_order", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("shadow_diff", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("shadow_diff", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("shadow_diff", "channel_account_id"): {"meaning": 'บัญชีช่องทางขายที่แถวอ้างอิง'},
    ("shadow_diff", "kind"): {"meaning": 'ชนิดความต่าง', "notes": 'enum: STOCK, ORDER, RESERVATION'},
    ("shadow_diff", "ref"): {"meaning": 'อ้างอิงสิ่งที่เทียบ (listing, order, reservation group)'},
    ("shadow_diff", "oms_value"): {"meaning": 'ค่าฝั่ง OMS เป็น JSON'},
    ("shadow_diff", "channel_value"): {"meaning": 'ค่าฝั่งช่องทางเป็น JSON'},
    ("shadow_diff", "observed_at"): {"meaning": 'เวลาที่พบความต่าง (UTC)'},
    ("shadow_diff", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("shipment", "id"): {"meaning": 'รหัสประจำการจัดส่ง (หนึ่งแถวต่อออเดอร์)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "order_id"): {"meaning": 'ออเดอร์ที่จัดส่งนี้สังกัด', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "warehouse_id"): {"meaning": 'คลังที่จัดส่งออก', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "carrier"): {"meaning": 'บริษัทขนส่ง', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "tracking_no"): {"meaning": 'เลขพัสดุ', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "external_shipment_id"): {"meaning": 'รหัส shipment ฝั่งช่องทาง/ขนส่ง', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "label_cached_until"): {"meaning": 'หมดอายุ cache ใบปะหน้า (ไม่เก็บ PDF ในฐานข้อมูล)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "status"): {"meaning": 'สถานะการจัดส่ง', "notes": 'enum: PENDING, LABEL_READY, SHIPPED, IN_TRANSIT, DELIVERED, FAILED, RETURNED_TO_SENDER; reserved [T18](../plan/05-task-list.md#L229)'},
    ("shipment", "shipped_at"): {"meaning": 'เวลาออกจากคลัง (UTC)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "delivered_at"): {"meaning": 'เวลาส่งถึงผู้รับ (UTC)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("shipment", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)', "notes": 'reserved [T18](../plan/05-task-list.md#L229) — ยังไม่มี writer บน main'},
    ("sku", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("sku", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("sku", "product_id"): {"meaning": 'product แม่ของ SKU'},
    ("sku", "sku_code"): {"meaning": 'รหัส SKU ภายในร้าน (ไม่ซ้ำต่อ tenant)'},
    ("sku", "name"): {"meaning": 'ชื่อที่แสดง'},
    ("sku", "barcode"): {"meaning": 'บาร์โค้ดสินค้า (ถ้ามี)'},
    ("sku", "weight_g"): {"meaning": 'น้ำหนักสินค้าเป็นกรัม'},
    ("sku", "is_bundle"): {"meaning": 'เป็น SKU แบบชุด (bundle) ที่ไม่ถือสต็อกเอง แต่ใช้ component'},
    ("sku", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("sku", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("sku_bundle_component", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("sku_bundle_component", "bundle_sku_id"): {"meaning": 'SKU ชุด (bundle) ที่มี component'},
    ("sku_bundle_component", "component_sku_id"): {"meaning": 'SKU ส่วนประกอบในชุด'},
    ("sku_bundle_component", "qty"): {"meaning": 'จำนวน component ต่อ 1 ชุด bundle'},
    ("sku_bundle_component", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("sku_bundle_component", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("stock_document", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("stock_document", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("stock_document", "type"): {"meaning": 'ประเภทเอกสารสต็อก', "notes": 'enum: OPENING, RECEIVE, ADJUSTMENT, COUNT, WRITE_OFF'},
    ("stock_document", "status"): {"meaning": 'สถานะเอกสาร', "notes": 'enum: DRAFT, POSTED, VOID; หลัง DRAFT แก้ได้แค่ status'},
    ("stock_document", "reference_no"): {"meaning": 'เลขอ้างอิงภายนอกของเอกสาร'},
    ("stock_document", "note"): {"meaning": 'หมายเหตุเอกสาร'},
    ("stock_document", "count_started_at"): {"meaning": 'เวลาเริ่มนับสต็อก (เฉพาะ type COUNT)'},
    ("stock_document", "posted_at"): {"meaning": 'เวลา post เอกสม (NULL ตอน DRAFT)'},
    ("stock_document", "posted_by"): {"meaning": 'รหัส app_user ที่ post (ไม่มี FK)'},
    ("stock_document", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("stock_document", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("stock_document_line", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("stock_document_line", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("stock_document_line", "document_id"): {"meaning": 'รหัสเอกสารแม่'},
    ("stock_document_line", "sku_id"): {"meaning": 'SKU OMS ที่แถวอ้างอิง'},
    ("stock_document_line", "warehouse_id"): {"meaning": 'คลังที่แถวอ้างอิง'},
    ("stock_document_line", "qty"): {"meaning": 'จำนวนในบรรทัด (ความหมายตามประเภทเอกสาร)'},
    ("stock_document_line", "system_qty_at_start"): {"meaning": 'ยอดระบบตอนเริ่มนับ (COUNT)'},
    ("stock_document_line", "counted_qty"): {"meaning": 'ยอดที่นับได้จริง (COUNT)'},
    ("stock_document_line", "reason_code"): {"meaning": 'รหัสเหตุผลปรับสต็อก (บังคับตอน post ADJUSTMENT)'},
    ("stock_document_line", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("stock_document_line", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("stock_reservation", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("stock_reservation", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("stock_reservation", "owner_type"): {"meaning": 'เจ้าของการจอง', "notes": 'enum: CHECKOUT, ORDER'},
    ("stock_reservation", "owner_ref"): {"meaning": 'อ้างอิงเจ้าของ (เช่น checkout id หรือ order id เป็น text)'},
    ("stock_reservation", "sku_id"): {"meaning": 'SKU OMS ที่แถวอ้างอิง'},
    ("stock_reservation", "warehouse_id"): {"meaning": 'คลังที่แถวอ้างอิง'},
    ("stock_reservation", "qty"): {"meaning": 'จำนวนที่จอง (ต่อ component SKU)'},
    ("stock_reservation", "status"): {"meaning": 'ACTIVE กำลังจอง, CONSUMED ตัดสต็อกเมื่อ ship, RELEASED คืนสต็อก, EXPIRED หมดเวลา/unpaid grace'},
    ("stock_reservation", "expires_at"): {"meaning": 'เวลาหมดอายุการจอง (UTC); NULL เมื่อชำระแล้วหรือไม่มี TTL'},
    ("stock_reservation", "reservation_group_id"): {"meaning": 'รหัสกลุ่มจองร่วมกัน (UUIDv7) ที่ส่งกลับ TSF เป็น reservation_id'},
    ("stock_reservation", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("stock_reservation", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("sync_cursor", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("sync_cursor", "channel_account_id"): {"meaning": 'บัญชีช่องทางที่ cursor นี้ผูก'},
    ("sync_cursor", "resource"): {"meaning": 'ทรัพยากรที่ sync', "notes": 'enum: ORDERS, LISTINGS'},
    ("sync_cursor", "cursor"): {"meaning": 'ตำแหน่ง cursor ล่าสุด (JSON updated_since/page_cursor)'},
    ("sync_cursor", "last_success_at"): {"meaning": 'เวลา sync สำเร็จล่าสุด (UTC)'},
    ("sync_cursor", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("sync_cursor", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'},
    ("tenant", "id"): {"meaning": 'รหัสประจำร้าน (tenant) หนึ่งแถวต่อ TSF shop'},
    ("tenant", "name"): {"meaning": 'ชื่อร้านที่แสดงใน OMS'},
    ("tenant", "tsf_shop_id"): {"meaning": 'รหัสร้านบน TSF (ไม่ซ้ำทั้งระบบ)'},
    ("tenant", "membership_tier"): {"meaning": 'แพ็กเกจ membership จาก TSF'},
    ("tenant", "entitlement_status"): {"meaning": 'สิทธิ์ใช้งาน OMS ของร้าน', "notes": 'enum: ACTIVE, GRACE, SUSPENDED เท่านั้น'},
    ("tenant", "entitlement_expires_at"): {"meaning": 'เวลาหมดอายุ subscription หรือช่วง GRACE'},
    ("tenant", "ent_ver"): {"meaning": 'เวอร์ชัน entitlement กันข้อมูล stale จาก JWT และ membership.changed'},
    ("tenant_membership", "id"): {"meaning": 'รหัสประจำความสัมพันธ์ user–tenant'},
    ("tenant_membership", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("tenant_membership", "user_id"): {"meaning": 'รหัสผู้ใช้ OMS (app_user)'},
    ("tenant_membership", "role"): {"meaning": 'บทบาทในร้าน', "notes": 'enum: OWNER, ADMIN, STAFF'},
    ("tenant_membership", "status"): {"meaning": 'สถานะการเป็นสมาชิก', "notes": 'enum: ACTIVE, REVOKED'},
    ("warehouse", "id"): {"meaning": 'รหัสประจำแถว (UUIDv7 ที่แอปสร้าง)'},
    ("warehouse", "tenant_id"): {"meaning": 'รหัสร้านที่แถวนี้สังกัด ใช้กรองด้วย RLS'},
    ("warehouse", "code"): {"meaning": 'รหัสคลังภายในร้าน'},
    ("warehouse", "name"): {"meaning": 'ชื่อที่แสดง'},
    ("warehouse", "address"): {"meaning": 'ที่อยู่คลังเป็น JSON (ไม่ใช่ PII ผู้รับ)'},
    ("warehouse", "is_default"): {"meaning": 'เป็นคลังหลักของร้าน (ได้มากสุดหนึ่งคลังต่อ tenant)'},
    ("warehouse", "created_at"): {"meaning": 'เวลาที่แถวถูกสร้าง (timestamptz UTC)'},
    ("warehouse", "updated_at"): {"meaning": 'เวลาที่แถวถูกแก้ไขล่าสุด (timestamptz UTC)'}
}

assert len(FIELDS) == 329
